# Generated by Django 3.2.5 on 2022-12-22 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0004_auto_20221222_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^(4)(\\d{7})$')])),
                ('img', models.ImageField(null=True, upload_to='Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
