# Generated by Django 3.2.5 on 2022-12-22 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0005_auto_20221222_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='img',
            new_name='images',
        ),
        migrations.AddField(
            model_name='student',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
