# Generated by Django 3.2.5 on 2022-12-22 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0006_auto_20221222_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('\\d{3}')])),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='images',
            field=models.ImageField(max_length=300, null=True, upload_to='Student'),
        ),
    ]
