# Generated by Django 3.2.5 on 2022-12-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0007_auto_20221222_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_absence',
            field=models.IntegerField(default=0),
        ),
    ]
