# Generated by Django 3.2.5 on 2022-12-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0008_student_student_absence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='images',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(max_length=300, null=True, upload_to='Student')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HadirApp.student')),
            ],
        ),
    ]
