# Generated by Django 3.2.5 on 2022-12-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0009_auto_20221222_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.FileField(max_length=300, null=True, upload_to='Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date registered'),
        ),
    ]
