# Generated by Django 3.2.5 on 2022-12-25 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0011_alter_image_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HadirApp.class'),
        ),
    ]
