# Generated by Django 3.2.5 on 2022-12-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0013_auto_20221225_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.FileField(max_length=300, null=True, upload_to='Hadir/HadirApp/media'),
        ),
    ]
