# Generated by Django 3.2.5 on 2022-12-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0014_alter_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.FileField(max_length=300, null=True, upload_to=''),
        ),
    ]
