# Generated by Django 3.2.5 on 2022-12-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0017_alter_image_img_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_id',
        ),
        migrations.AddField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
