# Generated by Django 3.2.5 on 2022-12-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0019_auto_20221225_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='student',
        ),
        migrations.AddField(
            model_name='image',
            name='student',
            field=models.ManyToManyField(null=True, to='HadirApp.Student'),
        ),
    ]
