# Generated by Django 3.2.5 on 2022-12-25 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0020_auto_20221225_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='student',
        ),
        migrations.AddField(
            model_name='image',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HadirApp.student'),
        ),
    ]
